// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock/repository.go
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	accounts "passman/internal/server/accounts"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// AddAccount mocks base method.
func (m *Mockrepository) AddAccount(ctx context.Context, newAccount accounts.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccount", ctx, newAccount)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAccount indicates an expected call of AddAccount.
func (mr *MockrepositoryMockRecorder) AddAccount(ctx, newAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccount", reflect.TypeOf((*Mockrepository)(nil).AddAccount), ctx, newAccount)
}

// GetAccountID mocks base method.
func (m *Mockrepository) GetAccountID(ctx context.Context, userID, serviceID uuid.UUID, credName string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountID", ctx, userID, serviceID, credName)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountID indicates an expected call of GetAccountID.
func (mr *MockrepositoryMockRecorder) GetAccountID(ctx, userID, serviceID, credName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountID", reflect.TypeOf((*Mockrepository)(nil).GetAccountID), ctx, userID, serviceID, credName)
}

// GetServiceID mocks base method.
func (m *Mockrepository) GetServiceID(ctx context.Context, serviceName string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceID", ctx, serviceName)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceID indicates an expected call of GetServiceID.
func (mr *MockrepositoryMockRecorder) GetServiceID(ctx, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceID", reflect.TypeOf((*Mockrepository)(nil).GetServiceID), ctx, serviceName)
}

// GetUserAccountsInService mocks base method.
func (m *Mockrepository) GetUserAccountsInService(ctx context.Context, params accounts.QueryParams) ([]accounts.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccountsInService", ctx, params)
	ret0, _ := ret[0].([]accounts.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccountsInService indicates an expected call of GetUserAccountsInService.
func (mr *MockrepositoryMockRecorder) GetUserAccountsInService(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccountsInService", reflect.TypeOf((*Mockrepository)(nil).GetUserAccountsInService), ctx, params)
}

// IsEmptyRows mocks base method.
func (m *Mockrepository) IsEmptyRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmptyRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEmptyRows indicates an expected call of IsEmptyRows.
func (mr *MockrepositoryMockRecorder) IsEmptyRows(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmptyRows", reflect.TypeOf((*Mockrepository)(nil).IsEmptyRows), err)
}

// RemoveAccount mocks base method.
func (m *Mockrepository) RemoveAccount(ctx context.Context, userID uuid.UUID, accountName, serviceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAccount", ctx, userID, accountName, serviceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAccount indicates an expected call of RemoveAccount.
func (mr *MockrepositoryMockRecorder) RemoveAccount(ctx, userID, accountName, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAccount", reflect.TypeOf((*Mockrepository)(nil).RemoveAccount), ctx, userID, accountName, serviceName)
}

// RemoveAllAccountsInService mocks base method.
func (m *Mockrepository) RemoveAllAccountsInService(ctx context.Context, userID uuid.UUID, serviceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllAccountsInService", ctx, userID, serviceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllAccountsInService indicates an expected call of RemoveAllAccountsInService.
func (mr *MockrepositoryMockRecorder) RemoveAllAccountsInService(ctx, userID, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllAccountsInService", reflect.TypeOf((*Mockrepository)(nil).RemoveAllAccountsInService), ctx, userID, serviceName)
}

// UpdateAccount mocks base method.
func (m *Mockrepository) UpdateAccount(ctx context.Context, oldServiceName string, updatedAccount accounts.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, oldServiceName, updatedAccount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockrepositoryMockRecorder) UpdateAccount(ctx, oldServiceName, updatedAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*Mockrepository)(nil).UpdateAccount), ctx, oldServiceName, updatedAccount)
}
