// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: starter.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const addAssets = `-- name: AddAssets :exec
insert into services (id, name, logo) values (?, ?, ?)
`

type AddAssetsParams struct {
	ID   uuid.UUID
	Name string
	Logo string
}

func (q *Queries) AddAssets(ctx context.Context, arg AddAssetsParams) error {
	_, err := q.db.ExecContext(ctx, addAssets, arg.ID, arg.Name, arg.Logo)
	return err
}

const addKeys = `-- name: AddKeys :exec
insert into ciphers (id, key_value) values (?, ?)
`

type AddKeysParams struct {
	ID       uuid.UUID
	KeyValue string
}

func (q *Queries) AddKeys(ctx context.Context, arg AddKeysParams) error {
	_, err := q.db.ExecContext(ctx, addKeys, arg.ID, arg.KeyValue)
	return err
}

const getKeys = `-- name: GetKeys :many
select key_value from ciphers
`

func (q *Queries) GetKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key_value string
		if err := rows.Scan(&key_value); err != nil {
			return nil, err
		}
		items = append(items, key_value)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
