// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: creds.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const addCredsRecord = `-- name: AddCredsRecord :exec
insert into creds (id, user_id, service_id, name, secret, payload) values (?, ?, ?, ?, ?, ?)
`

type AddCredsRecordParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ServiceID uuid.UUID
	Name      string
	Secret    int64
	Payload   string
}

func (q *Queries) AddCredsRecord(ctx context.Context, arg AddCredsRecordParams) error {
	_, err := q.db.ExecContext(ctx, addCredsRecord,
		arg.ID,
		arg.UserID,
		arg.ServiceID,
		arg.Name,
		arg.Secret,
		arg.Payload,
	)
	return err
}

const getCredsRecordID = `-- name: GetCredsRecordID :one
select id from creds where name = ? and service_id = ? and user_id = ?
`

type GetCredsRecordIDParams struct {
	Name      string
	ServiceID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetCredsRecordID(ctx context.Context, arg GetCredsRecordIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getCredsRecordID, arg.Name, arg.ServiceID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getServiceID = `-- name: GetServiceID :one
select id from services where name = ?
`

func (q *Queries) GetServiceID(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getServiceID, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserCredsInService = `-- name: GetUserCredsInService :many
select creds.id, creds.name, creds.secret, creds.payload from creds
  left join services on services.id = creds.service_id
  where creds.user_id = ? and services.name = ?
`

type GetUserCredsInServiceParams struct {
	UserID uuid.UUID
	Name   string
}

type GetUserCredsInServiceRow struct {
	ID      uuid.UUID
	Name    string
	Secret  int64
	Payload string
}

func (q *Queries) GetUserCredsInService(ctx context.Context, arg GetUserCredsInServiceParams) ([]GetUserCredsInServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserCredsInService, arg.UserID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCredsInServiceRow
	for rows.Next() {
		var i GetUserCredsInServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Secret,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllCredsInService = `-- name: RemoveAllCredsInService :exec
delete from creds
  where id in (
    select creds.id from creds
      left join services on services.id = creds.service_id
      where creds.user_id = ? and services.name = ?
  )
`

type RemoveAllCredsInServiceParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) RemoveAllCredsInService(ctx context.Context, arg RemoveAllCredsInServiceParams) error {
	_, err := q.db.ExecContext(ctx, removeAllCredsInService, arg.UserID, arg.Name)
	return err
}

const removeCredsRecord = `-- name: RemoveCredsRecord :exec
delete from creds
  where creds.user_id = ? and
  creds.name = ? and
  creds.service_id in (
    select services.id from services
      where services.name = ?3
  )
`

type RemoveCredsRecordParams struct {
	UserID      uuid.UUID
	Name        string
	ServiceName string
}

func (q *Queries) RemoveCredsRecord(ctx context.Context, arg RemoveCredsRecordParams) error {
	_, err := q.db.ExecContext(ctx, removeCredsRecord, arg.UserID, arg.Name, arg.ServiceName)
	return err
}

const updateCredsRecord = `-- name: UpdateCredsRecord :exec
update creds set name = ?, secret = ?, payload = ? where user_id = ? and name = ?5
`

type UpdateCredsRecordParams struct {
	Name    string
	Secret  int64
	Payload string
	UserID  uuid.UUID
	OldName string
}

func (q *Queries) UpdateCredsRecord(ctx context.Context, arg UpdateCredsRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateCredsRecord,
		arg.Name,
		arg.Secret,
		arg.Payload,
		arg.UserID,
		arg.OldName,
	)
	return err
}
