// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const addAccount = `-- name: AddAccount :exec
insert into accounts (id, user_id, service_id, name, secret, payload) values (?, ?, ?, ?, ?, ?)
`

type AddAccountParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ServiceID uuid.UUID
	Name      string
	Secret    int64
	Payload   string
}

func (q *Queries) AddAccount(ctx context.Context, arg AddAccountParams) error {
	_, err := q.db.ExecContext(ctx, addAccount,
		arg.ID,
		arg.UserID,
		arg.ServiceID,
		arg.Name,
		arg.Secret,
		arg.Payload,
	)
	return err
}

const getAccountID = `-- name: GetAccountID :one
select id from accounts where name = ? and service_id = ? and user_id = ?
`

type GetAccountIDParams struct {
	Name      string
	ServiceID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetAccountID(ctx context.Context, arg GetAccountIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getAccountID, arg.Name, arg.ServiceID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getServiceID = `-- name: GetServiceID :one
select id from services where name = ?
`

func (q *Queries) GetServiceID(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getServiceID, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserAccountsInService = `-- name: GetUserAccountsInService :many
select accounts.id, accounts.name, accounts.secret, accounts.payload from accounts
  left join services on services.id = accounts.service_id
  where accounts.user_id = ? and services.name = ?
`

type GetUserAccountsInServiceParams struct {
	UserID uuid.UUID
	Name   string
}

type GetUserAccountsInServiceRow struct {
	ID      uuid.UUID
	Name    string
	Secret  int64
	Payload string
}

func (q *Queries) GetUserAccountsInService(ctx context.Context, arg GetUserAccountsInServiceParams) ([]GetUserAccountsInServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAccountsInService, arg.UserID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAccountsInServiceRow
	for rows.Next() {
		var i GetUserAccountsInServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Secret,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAccount = `-- name: RemoveAccount :exec
delete from accounts
  where accounts.user_id = ? and
  accounts.name = ? and
  accounts.service_id in (
    select services.id from services
      where services.name = ?3
  )
`

type RemoveAccountParams struct {
	UserID      uuid.UUID
	Name        string
	ServiceName string
}

func (q *Queries) RemoveAccount(ctx context.Context, arg RemoveAccountParams) error {
	_, err := q.db.ExecContext(ctx, removeAccount, arg.UserID, arg.Name, arg.ServiceName)
	return err
}

const removeAllAccountsInService = `-- name: RemoveAllAccountsInService :exec
delete from accounts
  where id in (
    select accounts.id from accounts
      left join services on services.id = accounts.service_id
      where accounts.user_id = ? and services.name = ?
  )
`

type RemoveAllAccountsInServiceParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) RemoveAllAccountsInService(ctx context.Context, arg RemoveAllAccountsInServiceParams) error {
	_, err := q.db.ExecContext(ctx, removeAllAccountsInService, arg.UserID, arg.Name)
	return err
}

const updateAccount = `-- name: UpdateAccount :exec
update accounts set name = ?, secret = ?, payload = ? where user_id = ? and name = ?5
`

type UpdateAccountParams struct {
	Name    string
	Secret  int64
	Payload string
	UserID  uuid.UUID
	OldName string
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Name,
		arg.Secret,
		arg.Payload,
		arg.UserID,
		arg.OldName,
	)
	return err
}
