// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const addService = `-- name: AddService :exec
insert into services (id, name, logo) values (?, ?, ?)
`

type AddServiceParams struct {
	ID   uuid.UUID
	Name string
	Logo string
}

func (q *Queries) AddService(ctx context.Context, arg AddServiceParams) error {
	_, err := q.db.ExecContext(ctx, addService, arg.ID, arg.Name, arg.Logo)
	return err
}

const checkExistingRecord = `-- name: CheckExistingRecord :one
select accounts.id from accounts
  where accounts.user_id <> ?
  and accounts.service_id in (
    select services.id from services
      where services.name = ?
  )
`

type CheckExistingRecordParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) CheckExistingRecord(ctx context.Context, arg CheckExistingRecordParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, checkExistingRecord, arg.UserID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getService = `-- name: GetService :one
select id, logo from services where name = ?
`

type GetServiceRow struct {
	ID   uuid.UUID
	Logo string
}

func (q *Queries) GetService(ctx context.Context, name string) (GetServiceRow, error) {
	row := q.db.QueryRowContext(ctx, getService, name)
	var i GetServiceRow
	err := row.Scan(&i.ID, &i.Logo)
	return i, err
}

const getServicesList = `-- name: GetServicesList :many
select name, logo from services
`

type GetServicesListRow struct {
	Name string
	Logo string
}

func (q *Queries) GetServicesList(ctx context.Context) ([]GetServicesListRow, error) {
	rows, err := q.db.QueryContext(ctx, getServicesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServicesListRow
	for rows.Next() {
		var i GetServicesListRow
		if err := rows.Scan(&i.Name, &i.Logo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserServicesList = `-- name: GetUserServicesList :many
select distinct services.name, services.logo from services
  left join accounts on accounts.service_id = services.id
  where accounts.user_id = ?
`

type GetUserServicesListRow struct {
	Name string
	Logo string
}

func (q *Queries) GetUserServicesList(ctx context.Context, userID uuid.UUID) ([]GetUserServicesListRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserServicesList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserServicesListRow
	for rows.Next() {
		var i GetUserServicesListRow
		if err := rows.Scan(&i.Name, &i.Logo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeService = `-- name: RemoveService :exec
delete from services where name = ?
`

func (q *Queries) RemoveService(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, removeService, name)
	return err
}

const updateService = `-- name: UpdateService :exec
update services set name = ?, logo = ? where name = ?3
`

type UpdateServiceParams struct {
	Name    string
	Logo    string
	OldName string
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateService, arg.Name, arg.Logo, arg.OldName)
	return err
}
