// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock/repository.go
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	creds "passman/internal/server/creds"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// AddCredsRecord mocks base method.
func (m *Mockrepository) AddCredsRecord(ctx context.Context, newCreds creds.CredsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCredsRecord", ctx, newCreds)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCredsRecord indicates an expected call of AddCredsRecord.
func (mr *MockrepositoryMockRecorder) AddCredsRecord(ctx, newCreds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCredsRecord", reflect.TypeOf((*Mockrepository)(nil).AddCredsRecord), ctx, newCreds)
}

// GetCredsRecordID mocks base method.
func (m *Mockrepository) GetCredsRecordID(ctx context.Context, userID, serviceID uuid.UUID, credName string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredsRecordID", ctx, userID, serviceID, credName)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredsRecordID indicates an expected call of GetCredsRecordID.
func (mr *MockrepositoryMockRecorder) GetCredsRecordID(ctx, userID, serviceID, credName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredsRecordID", reflect.TypeOf((*Mockrepository)(nil).GetCredsRecordID), ctx, userID, serviceID, credName)
}

// GetServiceID mocks base method.
func (m *Mockrepository) GetServiceID(ctx context.Context, serviceName string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceID", ctx, serviceName)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceID indicates an expected call of GetServiceID.
func (mr *MockrepositoryMockRecorder) GetServiceID(ctx, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceID", reflect.TypeOf((*Mockrepository)(nil).GetServiceID), ctx, serviceName)
}

// GetUserCredsInService mocks base method.
func (m *Mockrepository) GetUserCredsInService(ctx context.Context, params creds.QueryParams) ([]creds.CredsRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCredsInService", ctx, params)
	ret0, _ := ret[0].([]creds.CredsRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCredsInService indicates an expected call of GetUserCredsInService.
func (mr *MockrepositoryMockRecorder) GetUserCredsInService(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCredsInService", reflect.TypeOf((*Mockrepository)(nil).GetUserCredsInService), ctx, params)
}

// IsEmptyRows mocks base method.
func (m *Mockrepository) IsEmptyRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmptyRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEmptyRows indicates an expected call of IsEmptyRows.
func (mr *MockrepositoryMockRecorder) IsEmptyRows(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmptyRows", reflect.TypeOf((*Mockrepository)(nil).IsEmptyRows), err)
}

// RemoveAllCredsInService mocks base method.
func (m *Mockrepository) RemoveAllCredsInService(ctx context.Context, userID uuid.UUID, serviceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllCredsInService", ctx, userID, serviceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllCredsInService indicates an expected call of RemoveAllCredsInService.
func (mr *MockrepositoryMockRecorder) RemoveAllCredsInService(ctx, userID, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllCredsInService", reflect.TypeOf((*Mockrepository)(nil).RemoveAllCredsInService), ctx, userID, serviceName)
}

// RemoveCredsRecord mocks base method.
func (m *Mockrepository) RemoveCredsRecord(ctx context.Context, userID uuid.UUID, credName, serviceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCredsRecord", ctx, userID, credName, serviceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCredsRecord indicates an expected call of RemoveCredsRecord.
func (mr *MockrepositoryMockRecorder) RemoveCredsRecord(ctx, userID, credName, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCredsRecord", reflect.TypeOf((*Mockrepository)(nil).RemoveCredsRecord), ctx, userID, credName, serviceName)
}

// UpdateCredsRecord mocks base method.
func (m *Mockrepository) UpdateCredsRecord(ctx context.Context, oldServiceName string, updatedCreds creds.CredsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredsRecord", ctx, oldServiceName, updatedCreds)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCredsRecord indicates an expected call of UpdateCredsRecord.
func (mr *MockrepositoryMockRecorder) UpdateCredsRecord(ctx, oldServiceName, updatedCreds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredsRecord", reflect.TypeOf((*Mockrepository)(nil).UpdateCredsRecord), ctx, oldServiceName, updatedCreds)
}
