// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock/repository.go
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	services "passman/internal/server/services"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// AddService mocks base method.
func (m *Mockrepository) AddService(ctx context.Context, newService services.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddService", ctx, newService)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddService indicates an expected call of AddService.
func (mr *MockrepositoryMockRecorder) AddService(ctx, newService any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddService", reflect.TypeOf((*Mockrepository)(nil).AddService), ctx, newService)
}

// CheckExistingRecord mocks base method.
func (m *Mockrepository) CheckExistingRecord(ctx context.Context, userID uuid.UUID, serviceName string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistingRecord", ctx, userID, serviceName)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistingRecord indicates an expected call of CheckExistingRecord.
func (mr *MockrepositoryMockRecorder) CheckExistingRecord(ctx, userID, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistingRecord", reflect.TypeOf((*Mockrepository)(nil).CheckExistingRecord), ctx, userID, serviceName)
}

// GetAllServices mocks base method.
func (m *Mockrepository) GetAllServices(ctx context.Context) ([]services.ServiceDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllServices", ctx)
	ret0, _ := ret[0].([]services.ServiceDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllServices indicates an expected call of GetAllServices.
func (mr *MockrepositoryMockRecorder) GetAllServices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllServices", reflect.TypeOf((*Mockrepository)(nil).GetAllServices), ctx)
}

// GetAllUserServices mocks base method.
func (m *Mockrepository) GetAllUserServices(ctx context.Context, userID uuid.UUID) ([]services.ServiceDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserServices", ctx, userID)
	ret0, _ := ret[0].([]services.ServiceDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserServices indicates an expected call of GetAllUserServices.
func (mr *MockrepositoryMockRecorder) GetAllUserServices(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserServices", reflect.TypeOf((*Mockrepository)(nil).GetAllUserServices), ctx, userID)
}

// GetService mocks base method.
func (m *Mockrepository) GetService(ctx context.Context, serviceName string) (services.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", ctx, serviceName)
	ret0, _ := ret[0].(services.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockrepositoryMockRecorder) GetService(ctx, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*Mockrepository)(nil).GetService), ctx, serviceName)
}

// IsEmptyRows mocks base method.
func (m *Mockrepository) IsEmptyRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmptyRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEmptyRows indicates an expected call of IsEmptyRows.
func (mr *MockrepositoryMockRecorder) IsEmptyRows(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmptyRows", reflect.TypeOf((*Mockrepository)(nil).IsEmptyRows), err)
}

// RemoveService mocks base method.
func (m *Mockrepository) RemoveService(ctx context.Context, serviceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveService", ctx, serviceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveService indicates an expected call of RemoveService.
func (mr *MockrepositoryMockRecorder) RemoveService(ctx, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveService", reflect.TypeOf((*Mockrepository)(nil).RemoveService), ctx, serviceName)
}

// UpdateService mocks base method.
func (m *Mockrepository) UpdateService(ctx context.Context, oldName string, updatedService services.ServiceDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateService", ctx, oldName, updatedService)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockrepositoryMockRecorder) UpdateService(ctx, oldName, updatedService any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*Mockrepository)(nil).UpdateService), ctx, oldName, updatedService)
}
