// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock/storage.go
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	creds "passman/cmd/internal/creds"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// AddNewCreds mocks base method.
func (m *Mockrepository) AddNewCreds(ctx context.Context, newCreds creds.ServiceDAO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewCreds", ctx, newCreds)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewCreds indicates an expected call of AddNewCreds.
func (mr *MockrepositoryMockRecorder) AddNewCreds(ctx, newCreds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewCreds", reflect.TypeOf((*Mockrepository)(nil).AddNewCreds), ctx, newCreds)
}

// FindCreds mocks base method.
func (m *Mockrepository) FindCreds(ctx context.Context, userID uuid.UUID, serviceName string) (creds.ServiceDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCreds", ctx, userID, serviceName)
	ret0, _ := ret[0].(creds.ServiceDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCreds indicates an expected call of FindCreds.
func (mr *MockrepositoryMockRecorder) FindCreds(ctx, userID, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCreds", reflect.TypeOf((*Mockrepository)(nil).FindCreds), ctx, userID, serviceName)
}

// GetCredsList mocks base method.
func (m *Mockrepository) GetCredsList(ctx context.Context, userID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredsList", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredsList indicates an expected call of GetCredsList.
func (mr *MockrepositoryMockRecorder) GetCredsList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredsList", reflect.TypeOf((*Mockrepository)(nil).GetCredsList), ctx, userID)
}

// IsEmptyRows mocks base method.
func (m *Mockrepository) IsEmptyRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmptyRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEmptyRows indicates an expected call of IsEmptyRows.
func (mr *MockrepositoryMockRecorder) IsEmptyRows(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmptyRows", reflect.TypeOf((*Mockrepository)(nil).IsEmptyRows), err)
}

// RemoveCreds mocks base method.
func (m *Mockrepository) RemoveCreds(ctx context.Context, userID uuid.UUID, serviceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCreds", ctx, userID, serviceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCreds indicates an expected call of RemoveCreds.
func (mr *MockrepositoryMockRecorder) RemoveCreds(ctx, userID, serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCreds", reflect.TypeOf((*Mockrepository)(nil).RemoveCreds), ctx, userID, serviceName)
}

// UpdateCreds mocks base method.
func (m *Mockrepository) UpdateCreds(ctx context.Context, oldServiceName string, updatedCreds creds.ServiceDAO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCreds", ctx, oldServiceName, updatedCreds)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCreds indicates an expected call of UpdateCreds.
func (mr *MockrepositoryMockRecorder) UpdateCreds(ctx, oldServiceName, updatedCreds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCreds", reflect.TypeOf((*Mockrepository)(nil).UpdateCreds), ctx, oldServiceName, updatedCreds)
}
