// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock/repository.go
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	reflect "reflect"

	users "passman/internal/server/users"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockdbRepo is a mock of dbRepo interface.
type MockdbRepo struct {
	ctrl     *gomock.Controller
	recorder *MockdbRepoMockRecorder
	isgomock struct{}
}

// MockdbRepoMockRecorder is the mock recorder for MockdbRepo.
type MockdbRepoMockRecorder struct {
	mock *MockdbRepo
}

// NewMockdbRepo creates a new mock instance.
func NewMockdbRepo(ctrl *gomock.Controller) *MockdbRepo {
	mock := &MockdbRepo{ctrl: ctrl}
	mock.recorder = &MockdbRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdbRepo) EXPECT() *MockdbRepoMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockdbRepo) AddUser(arg0 context.Context, arg1 users.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockdbRepoMockRecorder) AddUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockdbRepo)(nil).AddUser), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockdbRepo) GetUser(arg0 context.Context, arg1 string) (users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockdbRepoMockRecorder) GetUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockdbRepo)(nil).GetUser), arg0, arg1)
}

// GetUserByID mocks base method.
func (m *MockdbRepo) GetUserByID(arg0 context.Context, arg1 uuid.UUID) (users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockdbRepoMockRecorder) GetUserByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockdbRepo)(nil).GetUserByID), arg0, arg1)
}

// IsEmptyRows mocks base method.
func (m *MockdbRepo) IsEmptyRows(arg0 error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmptyRows", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEmptyRows indicates an expected call of IsEmptyRows.
func (mr *MockdbRepoMockRecorder) IsEmptyRows(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmptyRows", reflect.TypeOf((*MockdbRepo)(nil).IsEmptyRows), arg0)
}

// RemoveUser mocks base method.
func (m *MockdbRepo) RemoveUser(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUser indicates an expected call of RemoveUser.
func (mr *MockdbRepoMockRecorder) RemoveUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUser", reflect.TypeOf((*MockdbRepo)(nil).RemoveUser), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockdbRepo) UpdateUser(arg0 context.Context, arg1 users.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockdbRepoMockRecorder) UpdateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockdbRepo)(nil).UpdateUser), arg0, arg1)
}
