// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const addUser = `-- name: AddUser :exec
insert into users (id, username, password) values (?, ?, ?)
`

type AddUserParams struct {
	ID       uuid.UUID
	Username string
	Password string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser, arg.ID, arg.Username, arg.Password)
	return err
}

const getUser = `-- name: GetUser :one
select id, password from users where username = ?
`

type GetUserRow struct {
	ID       uuid.UUID
	Password string
}

func (q *Queries) GetUser(ctx context.Context, username string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select username, password from users where id = ?
`

type GetUserByIDRow struct {
	Username string
	Password string
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.Username, &i.Password)
	return i, err
}

const removeUser = `-- name: RemoveUser :exec
delete from users where id = ?
`

func (q *Queries) RemoveUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
update users set username = ?, password = ? where id = ?
`

type UpdateUserParams struct {
	Username string
	Password string
	ID       uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Username, arg.Password, arg.ID)
	return err
}
